# Generated by Django 4.2.5 on 2023-09-09 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_orderitems_order_customeraddres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddres',
            old_name='order',
            new_name='customer',
        ),
    ]
