# Generated by Django 4.2.5 on 2023-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_order_customeraddres_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddres',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
